### ISSUE TITLE
#120 – Updated Question Layout with GIF (Shanna’s questions) 

### ISSUE THREAD

**Issue by zuzivian** [cs394-w19/crush-it#17]
As a user, I want to view an initial set of quiz questions (Level 1) with a statement, gif, questions, and responses in a top-down scrollable screen so that I have a more engaging experience. 
- [ ] Top section (yellow area) :This will display the question preface.  Wrapped and taking up as much space as necessary to display the entire text. 
- [ ] Image 
- [ ] Question :This will display the actual question.  Wrapped and taking up as much space as necessary to display the entire text. 
- [ ] Response Options : Will either be in 2 option or 4 option multiple choice

**Comment by nicholson2208** [comment]
QuizQuestion component added in commit 9e34427 on branch make-quiz-question-component
