### ISSUE TITLE
BUG: Provide button on results screen that returns to level screen

### ISSUE THREAD

**Issue by zuzivian** [cs394-w19/crush-it#47]

**Comment by nicholson2208** [comment]
updated in 1fc524c. What should the text say?

**Comment by zuzivian** [comment]
> updated in [1fc524c](https://github.com/cs394-w19/crush-it/commit/1fc524c13294a8494ba5ab2224ee69463d05c7a0). What should the text say?

This was moved to the results screen so that the Crush-It! logo could be added to the top-left corner (for consistency)
